service_id = 2

[database]
host = "wicked-waifus-postgres:5432"
user_name = "wicked_waifus_user"
password = "wicked_waifus_pass"
db_name = "wicked_waifus_db"

[service_end_point]
addr = "tcp://0.0.0.0:10004"

[gateway_end_point]
addr = "tcp://wicked-waifus-gateway-server:10003"
